### ISSUE TITLE
Fuel - No Such Entity

### ISSUE THREAD

**Issue by Kingsman40** [MaDHouSe79/mh-npcservices#2]
When trying to use this script, I get
`script:mh-npcservcies GET_VEHICLE_FUEL_LEVEL: No such entity`

Can you change this so it gets the fuel from a fuel script like every other QB resource? For example, LegacyFuel. Most other QB scripts and QB jobs that spawn vehicles use this:
`exports['LegacyFuel']:SetFuel(vehicle, 100.0)`

**Comment by MaDHouSe79** [comment]
it uses the same native function as all other fuel scripts.

```lua
SetVehicleFuelLevel(vehicle, 100.0)
DecorSetFloat(vehicle, "_FUEL_LEVEL", GetVehicleFuelLevel(vehicle))
```

**Comment by sicksake1212** [comment]
sorry I too am having same issue with loads of this line so where abouts do I paste these two lines please

**Comment by MaDHouSe79** [comment]
> sorry I too am having same issue with loads of this line so where abouts do I paste these two lines please

I'm just guessing but if you get this error 'No such entity' it means that your vehicle is not recognised, this could mean that you don't have it in shared files or that your meta files are not good, by which I mean that the spawn name can be different then the model name, then you also get the same error, this happens more often with modded vehicles.

So it doesn't matter if you use a fuel script export or a native function from Fivem itself it comes down to the same thing because a fuel script uses the same native function as I do so essentially you don't need that export at all, because the fuel script calls the same native functions to get the fuel from a vehicle but also put it back with a native function. so it's the same thing.

here is a fuel script from LegacyFuel.
```lua
-- this function returns the fuel that i just set the with the native functions.
function GetFuel(vehicle)
	return DecorGetFloat(vehicle, Config.FuelDecor)
end

-- for: exports['LegacyFuel']:SetFuel(vehicle, 100.0)
function SetFuel(vehicle, fuel)
	if type(fuel) == 'number' and fuel >= 0 and fuel <= 100 then
		SetVehicleFuelLevel(vehicle, fuel + 0.0) -- <---- same as i use
		DecorSetFloat(vehicle, Config.FuelDecor, GetVehicleFuelLevel(vehicle)) -- <---- same as i use, to set a DecorGetFloat
	end
end
```

and even when you replace it with `exports['LegacyFuel']:SetFuel(vehicle, 100.0)` you can still have that error as I explained above.

almost every fuel script works the same, but I don't want to be depend on that, 
so I use the native functions from FiveM so it should always work provided your vehicles meta's are good.

mh-parking works in the same way and does not depend on a fuel script but the fuel works always.

**Comment by sicksake1212** [comment]
yes, I use your parking script also and works a treat with no errors only error with the npc but I will double check with the meta's all the same.
